services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TheCodingOwl\Oclock\:
        resource: '../Classes/*'

    TheCodingOwl\Oclock\Controller\ReminderController:
        public: true

    TheCodingOwl\Oclock\Toolbar\Clock:
        public: true

    TheCodingOwl\Oclock\Widgets\ClockWidget:
        arguments: ['theCodingOwlClock']
        tags:
            - name: dashboard.widget
              identifier: theCodingOwlClock
              widgetGroups: 'systemInfo'
