services:
    TheCodingOwl\Oclock\Widgets\ClockWidget:
        arguments: ['theCodingOwlClock']
        tags:
            - name: dashboard.widget
              identifier: theCodingOwlClock
              widgetGroups: 'systemInfo'
