name: lint

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: ESLint Action
      uses: stefanoeb/eslint-action@1.0.2

    - name: CSSLint Action
      run: ./node_modules/.bin/csslint --exclude-list=node_modules --exclude=public .
