name: phpstan

on:
  pull_request:
    branches: [ master ]
    
jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer install
      uses: php-actions/composer@v1

    - name: Composer require typo3/cms-dashboard
      uses: php-actions/composer@v1
      with:
        command: require typo3/cms-dashboard:^10.3.0

    - name: Run phpstan
      uses: franzliedke/gh-action-php@0.2.0
      with:
        runs: php7.3 ./vendor/bin/phpstan analyse Classes