name: phpstan

on:
  pull_request:
    branches: [ master ]
    
jobs:
  analyse:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Composer install
      uses: php-actions/composer@v1

    - name: Composer require typo3/cms-dashboard
      uses: ./.github/actions/install-typo3-cms-dashboard

    - name: Run phpstan
      uses: ./.github/actions/run-phpstan