name: Publish on TER

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: the-coding-owl/action-typo3-extension-repository-upload@0.0.1
      env: 
        SECRET_USERNAME: ${{ secrets.USERNAME }}
        SECRET_PASSWORD: ${{ secrets.PASSWORD }}
        EXTENSION_KEY: 'oclock'
        UPLOAD_MESSAGE: ${{ github.event.release.body }}
