name: "TYPO3 10 Test"

on:
  pull_request:
    branches: [ master ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cache composer dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ./.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Init composer.json"
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          command: init
          args: -n --name the-coding-owl/typo3test --require typo3/minimal:^10.4 --require typo3/cms-dashboard:^10.4

      - name: "Allow typo3/cms-composer-installers"
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          command: config
          args: --no-plugins allow-plugins.typo3/cms-composer-installers true

      - name: "Allow typo3/class-alias-loader"
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          command: config
          args: --no-plugins allow-plugins.typo3/class-alias-loader true

      - name: "Install oclock extension"
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          command: require the-coding-owl/oclock:dev-master -n --no-progress --no-audit

      - name: "Composer install dev dependencies"
        uses: php-actions/composer@v6
        with:
          php_version: 7.2
          command: install
          args: -n --dev --no-progress

      - name: Run PHP_CodeSniffer
        uses: public/typo3conf/ext/oclock/.github/actions/run-phpcs public/typo3conf/ext/oclock/

      - name: Run phpstan
        uses: public/typo3conf/ext/oclock/.github/actions/run-phpstan public/typo3conf/ext/oclock/
