name: "TYPO3 13 Test"

on:
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout oclock source"
        uses: actions/checkout@v3

      - name: Cache composer dependencies
        uses: actions/cache@v1
        env:
          cache-name: cache-composer-dependencies
        with:
          path: ./.composer/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: "Run tests"
        uses: php-actions/composer@v6
        with:
          php_version: 8.4
          php_extensions: intl
          command: run testTYPO3v13
